### ISSUE TITLE
或许是windows的老问题？

### ISSUE THREAD

**Issue by FCSfish** [Gawain-Chen/UZIP2#1]
试了一宿发现是系统语言编码从gb变成utf后路径就不可用了，必须全英文
但是我看cmd似乎还是可以用utf的，不知道什么情况
完全的萌新小白所以请大佬看看有什么办法，拜托了

**Comment by Gawen520** [comment]
@FCSfish 
cmd默认使用的是GBK编码，若改成UTF-8编码，建议先传入“chcp 65001”命令或改变传入字符串编码，用日志记录传入传出路径多试试。

**Comment by FCSfish** [comment]
> @FCSfish cmd默认使用的是GBK编码，若改成UTF-8编码，建议先传入“chcp 65001”命令或改变传入字符串编码，用日志记录传入传出路径多试试。

试了一个上午了，确定是windows整个操作系统的老问题，算了，大不了就用的时候换成gbk，不用重启一下换回来就好了（）

**Comment by Gawen520** [comment]
好的，欢迎提PR
